### ISSUE TITLE
TA_Initalize, TA_Shutdown unresolved (Windows DLL only)

### ISSUE THREAD

**Issue by tombrincil** [TA-Lib/ta-lib#52]
TA_Initalize, TA_Shutdown are not exported and they are unresolved external symbols when added to a project.

**Comment by mario4tier** [comment]
Thanks for reporting an issue. Are you trying DLL/Shared library or static links? Which of the TA-Lib package did you install?

**Comment by tombrincil** [comment]
I am using import library and DLL on Windows. The installed package is version 0.6.2

**Comment by mario4tier** [comment]
Thanks. I will try to fix this over the week-end.

**Comment by mario4tier** [comment]
This should now work with the 0.6.3 release.

Thanks again for reporting issues.
